package com.cnds.demo1.bean.repository.mg;

import com.cnds.demo1.bean.mg.TestName;
import com.cnds.demo1.bean.mg.TestNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    long countByExample(TestNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int deleteByExample(TestNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int insert(TestName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int insertSelective(TestName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    List<TestName> selectByExample(TestNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    TestName selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") TestName record, @Param("example") TestNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int updateByExample(@Param("record") TestName record, @Param("example") TestNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int updateByPrimaryKeySelective(TestName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    int updateByPrimaryKey(TestName record);
}