package com.cnds.demo1.bean.mg;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pid
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    private Integer pid;


   /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pname
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pprices
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    private Double pprices;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pid
     *
     * @return the value of goods.pid
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pid
     *
     * @param pid the value for goods.pid
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pname
     *
     * @return the value of goods.pname
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pname
     *
     * @param pname the value for goods.pname
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pprices
     *
     * @return the value of goods.pprices
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    public Double getPprices() {
        return pprices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pprices
     *
     * @param pprices the value for goods.pprices
     *
     * @mbg.generated Thu Jul 08 14:33:29 CST 2021
     */
    public void setPprices(Double pprices) {
        this.pprices = pprices;
    }
}