package com.cnds.demo1.bean.mg;

public class TestName {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_name.id
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_name.name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_name.age
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_name.city
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_name.id
     *
     * @return the value of test_name.id
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_name.id
     *
     * @param id the value for test_name.id
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_name.name
     *
     * @return the value of test_name.name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_name.name
     *
     * @param name the value for test_name.name
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_name.age
     *
     * @return the value of test_name.age
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_name.age
     *
     * @param age the value for test_name.age
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_name.city
     *
     * @return the value of test_name.city
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_name.city
     *
     * @param city the value for test_name.city
     *
     * @mbg.generated Thu Jul 08 14:08:33 CST 2021
     */
    public void setCity(String city) {
        this.city = city;
    }
}